### ISSUE TITLE
Fastboot Compatibility 

### ISSUE THREAD

**Issue by thefuzz80** [altrim/ember-cli-tooltipster#30]
I have interest in fastboot compatibility.  I've started working on it but get ```ReferenceError: jQuery is not defined``` when I serve the addon.

**Comment by altrim** [comment]
In this commit https://github.com/altrim/ember-cli-tooltipster/commit/e54431bc67c6b3979bd3fb40bd5597e7b162378e I removed the lib from the FastBoot build.

**Comment by thefuzz80** [comment]
Cool. I have done some work on a PR that did the same thing but I was stuck on whether or not to get the dummy app working under fastboot. As of right now the dummy app will work only if ember-paper is bumped to their alpha. Only drawback is that the dummy app does not "look" right.

**Comment by altrim** [comment]
I don't think it's necessary to get the dummy app working on FastBoot. Since the addon is based on jQuery plugin the demo requires that to work. As for `ember-paper` the demo app should work now with the old `0.2.14` version. I haven't tried the newer versions for `ember-paper` so I don't know if it will work with that.

**Comment by thefuzz80** [comment]
I think that is totally fair. Just wanted to be thorough. Since you made the change that my PR would have I will just close this issue. Thanks!
